#-------------------------------
# General Site Settings

title: Ayla Tolosa-Kline
description: Storyteller // Marketer // Thinker
email: hello@ayla-tk.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A portfolio of the work of Ayla Tolosa-Kline.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-106119862-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Ayla specializes in storytelling**; whether through writing, social media, video, photography or stats, she'll tell the story behind your organization, product or idea. She has a fancy MPH degree and years of strategic marketing under her belt, making her a **kick-ass marcom** advisor for public health agencies and health tech companies.





#-------------------------------
# Work Section

projects:
- {name: Turning Clicks into Health Action, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Giving Life to a Product, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: City-Wide Zika Prevention Campaign, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Website Refresh, folder: 'proj-4', file: 'work/proj-4.html'}






#-------------------------------
# Clients Section

clients:
- {avatar: 'face-tamar.jpg',
  name: 'Tamar Shen-Orr',
  title: 'Product Manager, CodeLovers IL',
  quote: '<p><strong>Ayla is a super-creative marketer who can be trusted to Get Things Done. She has the skills and insight to take a project from strategy phases to execution and then in analysis. Moreover, she has the motivation and grit to work around hurdles, find solutions within limited budgets, time-frames etc. </p>',
  logo: 'logo-einstein.jpg'}
- {avatar: 'face-melinda.jpg',
  name: 'Melinda Salmon',
  title: 'Program Manager at Centers for Disease Control and Prevention',
  quote: '<p><strong>Innovative, creative and forward-thinking are the words that I would use to describe Ayla. I had the pleasure of working with Ayla at the Philadelphia Department of Health. Ayla was our social media lead on the Take Control Philly campaign, an initiative we launched to increase the acceptability and availability of condoms among adolescents in Philadelphia. Ayla has a fantastic ability to create scenes that are eye-catching and interesting, whether in social media advertisement, traditional media or presentations. And she has a fantastic sense of humor. I always left our meetings smiling. In summary, I would recommend Ayla without hesitation.</p>',
  logo: 'logo-cdc.jpeg'}



#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/aylatk'}
- {icon: 'instagram', link: 'https://www.instagram.com/lightpursuits/'}
- {icon: 'youtube', link: 'https://www.youtube.com/playlist?list=PL9AnApVRe6j7fKz6n_TuvRGMo7L0pKNWx'}



# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
